# Generated by Django 5.1.5 on 2025-05-05 23:22

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('entry', 'Entry Level'), ('mid', '1-2 years'), ('senior', '3-4 years')], max_length=16)),
                ('work_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], max_length=20)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
